title: Karthik Ragubathy # The title of the blog
author: Karthik Ragubathy # Your name
email: me@pkarthik.in # your email shown in the footer
url: https://pkarthikr.github.io # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  Karthik's Weblog
favicon: "./favicon.ico" # set the favicon of the site
show_excerpts: false # set to true to show excerpts on the homepage

moving:
  avatar_url: "https://i.loli.net/2019/08/26/JzCLhDWPEybZr2T.jpg" # avatar in about page
  about_you: a short description about you. # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    twitter: pkarthikr
    github: pkarthikr
    linkedin: pkarthikr

# Build settings
remote_theme: huangyz0918/moving

plugins:
  - jekyll-feed
  - jekyll-seo-tag
